site_name: REV23 (CloudApp) Docs
site_description: 'REV23 (CloudApp) Docs'
site_author: 'REV23'
site_url: 'https://docs.rev23.com/rev23-cloudapp-docs/'

markdown_extensions:
  - meta
  - toc
  - tables
  - fenced_code
  - smarty
  - sane_lists
  - admonition

# Copyright
copyright: 'Copyright &copy; 2025 REV23'

#Navigation
nav:
    - Home: index.md
    - Overview: overview.md
    - Terminology: terminology.md
    - Concepts:    
      - 'REV23 ID': concepts/rev23-id.md 
      - 'Platforms': concepts/platforms.md 
      - 'Customers': concepts/customers.md
      - 'Services': concepts/services.md            
      - 'Kiosk': concepts/kiosk.md
      - 'Leads': concepts/leads.md
      - 'Templates': concepts/templates.md      
      - 'Users': concepts/users.md
      - 'Webhooks': concepts/webhooks.md
    - Settings:
      - Security:
        - 'Studios': settings/studios.md      
        - 'Users': settings/users.md
      - Customers:
        - 'Flags': settings/flags.md
        - 'Medical Conditions': settings/medical-conditions.md
        - 'Sources': settings/sources.md
      - Services:
        - 'Service Types': settings/service-types.md
        - Templates:
          - 'Designer': settings/templates/designer.md
          - 'Template Mappings': settings/templates/mappings.md
      - Tattoo: 'settings/tattoo.md'
      - Piercing: 'settings/piercing.md'
      - Needles: 'settings/needles.md'
      - iPad:
        - 'Portfolio': ipad/portfolio.md
        - 'Passcode': ipad/passcode.md
        - 'Cache': ipad/cache.md
      - API:
        - 'Overview': api/overview.md
        - 'Status Codes': api/status-codes.md
      - Versions:
        - 'iOS': versions/ios.md
        - 'Web': versions/web.md
    - About:
      - 'License': license.md
      - 'Release Notes': release-notes.md

# Theme
theme: 
  logo: 'img/logo.svg'
  name: material
  palette:
    primary: 'blue'
    accent: 'pink'
  favicon: 'img/favicon.ico'  

#Repository
repo_name: 'rev23docs/rev23-cloudapp-docs'
repo_url: 'https://github.com/rev23docs/rev23-cloudapp-docs'

# Customization
extra:
  social:
    - icon: 'fontawesome/brands/instagram'
      link: 'https://instagram.com/rev23dev'
    - icon: 'fontawesome/brands/facebook'
      link: 'https://facebook.com/rev23dev'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/rev23docs'
  disqus: 'rev23docs'

# Google Analytics
extra:
  analytics:
    provider: google
    property: UA-127274992-1